### PR TITLE
chore(button): not-allowed property when button is disabled

### PR DESCRIPTION
**Pull request by rands0n**
The state of the button should be `not-allowed` when the state is set to `disabled`.

### CODE REVIEW

**Comment by rands0n** [comment]
Looks like the rule of stylelint is unknow: `media-feature-parentheses-space-inside`

Can anyone review this to me?

The tests are failing on my machine too 😢

**Comment by jonrohan** [comment]
> Looks like the rule of stylelint is unknow: media-feature-parentheses-space-inside

Sorry, I updated the stylelint-config that this pr is using, but haven't updated the stylelint version dependency here. Will be updating it soon.

I think this is a good change though, @broccolini @mdo any reservations on having a `not-allowed` cursor on our disabled buttons? Looks like it's supported by all our browsers http://caniuse.com/#search=not-allowed

**Comment by rands0n** [comment]
@jonrohan any update on this?

**Comment by broccolini** [comment]
I am not sure I would change the default here. Feels like a non-standard implementation. Here's a related discussion only it's on button pointers that I think makes some valid points about the defaults: https://github.com/necolas/normalize.css/issues/371#issuecomment-60072171

I did some reading and it doesn't seem like this is a widely common practice, the most common reason being that it draws attention to elements that aren't able to be interacted with, and that there is non-standard implementation across browsers - i.e. it used to be red in Windows, having trouble finding what it looks like now. Firefox also ripped not-allowed out from their settings page: https://bugzilla.mozilla.org/show_bug.cgi?id=1219861

I'd probably opt to keep it as default, however I see Bootstrap is using it so I'm guessing @mdo has opinions on this.

**Comment by rands0n** [comment]
any update on this?

**Comment by jonrohan** [comment]
I talked with the team and we feel like changing this isn't default browser behavior. We'd also note that `not-allowed` is semantically different than `disabled`. 

So I'm going to close this PR. Thanks for the input though 💯

**Pull request closed without merging**
